Plant_database_app/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register', views.SignUpView.as_view(), name='register'),
]

Plant_database_app/plant_database/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('plant_view/', include('plant_view.urls')),
    path('', include('home.urls')),
]

Plant_database_app/plant_view/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "plant_view" # applicaition namespace
urlpatterns = [
        # Plant list, plant related urls:
        path('', views.MainView.as_view(), name='all'),
        path('main/myplants/', views.MyPlantsView.as_view(), name='plant_myplants'),
        path('main/create/', views.PlantCreateView.as_view(), name='plant_create'),
        path('main/<int:pk>/', views.PlantDetailView.as_view(), name='plant_detail'),
        path('main/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant_update'),
        path('main/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant_delete'),

        # Plant type related urls:
        path('ptview', views.PlantTypeListView.as_view(), name='planttype_list'),
        path('ptview/<int:pk>/', views.PlantTypeDetailView.as_view(), name='planttype_detail'),
        path('ptview/create/', views.PlantTypeCreate.as_view(), name='planttype_create'),
        path('ptview/<int:pk>/update/', views.PlantTypeUpdate.as_view(), name='planttype_update'),
        path('ptview/<int:pk>/delete/', views.PlantTypeDelete.as_view(), name='planttype_delete'),

        # Plant timeline related urls:
        path('main/<int:pk>/createevent/', views.PlantEventCreateView.as_view() , name='plantevent_create'),
        # path('ptevent/<int:pk>/update/', , name='planteventupdate'),
        # path('ptevent/<int:pk>/delete/', , name='plantevent_delete'),
    ]

Plant_database_app/plant_view/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy as _


class PlantType(models.Model):
    '''
    Stored a plant type name for statistical analysis
    
    (Plant's latin name or any descriptive name)
    Examples: Dendrobium Nobile, Cactus with small yellow flower
    '''
    name = models.CharField(
        max_length=128,
        validators=[ 
            MinLengthValidator(4, "Name should contain more, than 4 characters."),
        ]
        )
    
    def __str__(self):
        return self.name
    
class Location(models.Model):
    """
    Represents a location, where plants can be.
    """
    name = models.CharField(
        max_length=128,
        validators=[ 
            MinLengthValidator(4, "Name should contain more, than 4 characters."),
        ]
        )
    

    def __str__(self):
        return self.name
    

    
class Plant(models.Model):
    '''
    Stores an instance of a plant in the plant database
    '''
    name = models.CharField(max_length=64)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    plant_type = models.ForeignKey(PlantType, on_delete=models.CASCADE)
    events = models.ManyToManyField(settings.AUTH_USER_MODEL, through='DurationPlantEvent',
                                    related_name='plants_events')
    # location = models.ForeignKey(Location, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class PlantEvent(models.Model):
    '''
    Stores an event in the plant's timeline.
    TODO: handle differently events with a duration (like flowering)
    '''
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=1000)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} (UNDEFINED)"
    
class DurationPlantEvent(PlantEvent):
    class DurationEventTypeChoices(models.TextChoices):
        FLOWERING = "FL", _("Flowering")
        GROWING = "GR", _("Growing")

    start_date = models.DateField()
    end_date = models.DateField()
    event_type = models.CharField(
         max_length=20,
         choices=DurationEventTypeChoices.choices,
         default=DurationEventTypeChoices.FLOWERING
    )

    def __str__(self):
            return f"{self.title} ({self.start_date} - {self.end_date})"

    
# class StaticPlantEvent(PlantEvent):
#     date = models.DateTimeField()

#     def __str__(self):
#             return f"{self.title} ({self.date})"

Plant_database_app/plant_view/forms.py
from django import forms

from .models import Plant, DurationPlantEvent

class PlantCreateForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = ['name', 'plant_type']

class DurationPlantEventCreateForm(forms.ModelForm):
    class Meta:
        model = DurationPlantEvent
        fields = ['title', 'description', 'start_date', 'end_date', 'event_type']

Plant_database_app/plant_view/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from plant_view.models import Plant, PlantType, DurationPlantEvent
from plant_view.forms import PlantCreateForm, DurationPlantEventCreateForm


log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# PLANT RELATED VIEWS
class MainView(LoginRequiredMixin, View):
    def get(self, request):
        plant_list = Plant.objects.all()
        plant_type_list = PlantType.objects.all()

        context = {
            'plant_list': plant_list,
            'plant_type_list': plant_type_list,
        }
        return render(request, 'plant_view/plant_list.html', context)
    
class MyPlantsView(LoginRequiredMixin, View):
    def get(self, request):
        plant_list = Plant.objects.all().filter(user=self.request.user)

        context = {
            'plant_list': plant_list,
        }
        return render(request, 'plant_view/my_plant_list.html', context)
    
class PlantDetailView(LoginRequiredMixin, DeleteView):
    def get(self, request, pk):
        current_plant = get_object_or_404(Plant, id=pk)
        plant_timeline = DurationPlantEvent.objects.filter(plant=current_plant)
        event_form = DurationPlantEventCreateForm()
        context = {
            'plant': current_plant,
            'plant_timeline': plant_timeline,
            'event_form': event_form,
        }
        return render(request, 'plant_view/plant_detail.html', context)
    

class PlantCreateView(LoginRequiredMixin, View):
    success_url = reverse_lazy("plant_view:all")
    template_name = 'plant_view/plant_form.html'

    def get(self, request, pk=None):
        logging.info("Plant create form GET called")
        log.info("")
        form = PlantCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk=None):
        logging.info("Plant create form POST called")
        form = PlantCreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            logging.info("Plant create form is not valid, return.")
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        plant = form.save(commit=False)
        plant.user = self.request.user
        plant.save()
        logging.info("Plant create form POST done, to be redirected...")
        return redirect(self.success_url)

class PlantUpdate(LoginRequiredMixin, UpdateView):
    success_url = reverse_lazy("plant_view:all")
    template_name = 'plant_view/plant_form.html'

    def get(self, request, pk=None):
        plant = get_object_or_404(Plant, id=pk, user=self.request.user)
        form = PlantCreateForm(instance=plant)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk=None):
        plant = get_object_or_404(Plant, id=pk, user=self.request.user)
        form = PlantCreateForm(request.POST, request.FILES or None, instance=plant)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        plant = form.save(commit=False)
        plant.save()
        return redirect(self.success_url)


class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    fields = "__all__"
    success_url = reverse_lazy("plant_view:all")

    def get_queryset(self):
        qs = super(DeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)


# PLANT TYPE RELATED VIEWS
class PlantTypeListView(LoginRequiredMixin, View):
    def get(self, request):
        planttype_list = PlantType.objects.all()

        context = {
            'planttype_list': planttype_list,
        }
        return render(request, 'plant_view/planttype_list.html', context)
    
class PlantTypeDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        current_plant_type = get_object_or_404(PlantType, id=pk)
        plant_count = Plant.objects.all().filter(plant_type=current_plant_type).count()

        context = {
            'planttype': current_plant_type,
            'plantcount': plant_count,
        }
        return render(request, 'plant_view/planttype_detail.html', context)
    
class PlantTypeCreate(LoginRequiredMixin, CreateView):
    # CreateView basically does the same things as above:
    model = PlantType
    fields = "__all__"
    success_url = reverse_lazy("plant_view:planttype_list")

class PlantTypeUpdate(LoginRequiredMixin, UpdateView):
    model = PlantType
    fields = "__all__"
    success_url = reverse_lazy("plant_view:planttype_list")

class PlantTypeDelete(LoginRequiredMixin, DeleteView):
    model = PlantType
    fields = "__all__"
    success_url = reverse_lazy("plant_view:planttype_list")


# PLANT EVENT, TIMELINE RELATED VIEWS:
class PlantEventCreateView(LoginRequiredMixin, View):
    
    def post(self, request, pk):
        p = get_object_or_404(Plant, id=pk)

        print("DEBUG:", pk, p)
        print(request.POST)
        plant_event = DurationPlantEvent(
            title=request.POST['title'],
            description=request.POST['description'],
            plant=p,
            author=request.user,
            start_date=request.POST['start_date'],
            end_date=request.POST['end_date'],
            event_type=request.POST['end_date'],
            )
        plant_event.save()
        return redirect(reverse('plant_view:plant_detail', args=[pk]))

Plant_database_app/plant_view/templates/plant_view/my_plant_list.html
{% extends "navbar.html" %}

{% block content %}
  <h1>Plant List</h1>
  <p>
    <a href="{% url 'plant_view:plant_create' %}">Add a new plant!</a>
  </p>

  {% if plant_list %}
  <p>My plant list:</p>
  <ul>
    {% for plant in plant_list %}
      <li>
          <a href="{% url 'plant_view:plant_detail' plant.id %}">{{ plant.name}}</a>  - (<a href="{% url 'plant_view:planttype_detail' plant.plant_type.id %}">{{ plant.plant_type }}</a>)
          (<a href="{% url 'plant_view:plant_update' plant.id %}">Update</a> |
          <a href="{% url 'plant_view:plant_delete' plant.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>

  {% else %}
    <p>There are no plants made yet.</p>
  {% endif %}
  
{% endblock %}

Plant_database_app/plant_view/templates/plant_view/plant_confirm_delete.html
{% extends "navbar.html" %}

{% block content %}

<h1>Delete Plant</h1>

<p>Are you sure you want to delete the plant: {{ plant }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

Plant_database_app/plant_view/templates/plant_view/plant_detail.html
{% extends "navbar.html" %}

{% load django_bootstrap5 %}
{% load static %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static "plant_view/style.css" %}">

{% endblock %}

{% block content %}

<span style="float: right;">
    {% if plant.user == user %}
        <a href="{% url 'plant_view:plant_update' plant.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'plant_view:plant_delete' plant.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
</span>

<h1>{{ plant.name }}</h1>

<p>Creator: {{ plant.user }}</p>

<p>Plant type: <a href="{% url 'plant_view:planttype_detail' plant.plant_type.id %}">{{ plant.plant_type }}</a></p>




{% if plant_timeline %}
    <p>Plant events:</p>
    <ul style="list-style-type:none;">
        {% for event in plant_timeline %}
        <li class="plantevent">
            <div>
                <div class="topright">[{{event.start_date|date:"SHORT_DATE_FORMAT"}} - {{event.end_date|date:"SHORT_DATE_FORMAT"}}]</div>
                <div class="title">{{event.title}}</div>

            </div>
            <p> {{event.description}}</p>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No plant events added yet.</p>
{% endif %}

<p>Add a new plant event:</p>
{% if user.is_authenticated %}
    <br clear="all"/>
    <form method="post" action="{% url 'plant_view:plantevent_create' plant.id %}">
        {% csrf_token %}
        {% bootstrap_form event_form %}
        <input type="submit" value="Submit"/>
    </form>
{% endif %}

<p><a href="{% url 'plant_view:all' %}">To All Plants</a></p>
<p><a href="{% url 'plant_view:plant_myplants' %}">To My Plants</a></p>

{% endblock %}

Plant_database_app/plant_view/templates/plant_view/plant_form.html
{% extends "navbar.html" %}

{% load django_bootstrap5 %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {% bootstrap_form form %}
        </table>

        <input type="submit" value="Submit">
        <input type="submit" onclick="javascript:history.go(-1);" value="Cancel">
        {% comment %} <a href="{% url 'plant_view:all' %}">Cancel</a> {% endcomment %}
    </form>
{% endblock %}

Plant_database_app/plant_view/templates/plant_view/plant_list.html
{% extends "navbar.html" %}


{% block content %}
  <h1>Plant List</h1>
  <p>
    <a href="{% url 'plant_view:plant_create' %}">Add a new plant!</a>
  </p>

  {% if plant_list and plant_type_list %}
  <p>Plant list:</p>
  
  {% for plant_type in plant_type_list %}
    <p>{{ plant_type.name }}:</p>
    <ul>
    {% for plant in plant_list %}
      {% if plant.plant_type == plant_type %}
        <li>
          <a href="{% url 'plant_view:plant_detail' plant.id %}">{{ plant.name}}</a>  - (<a href="{% url 'plant_view:planttype_detail' plant.plant_type.id %}">{{ plant.plant_type }}</a>)
        </li>
      {% endif %}
    {% endfor %}
    </ul>
  {% endfor %}

  {% else %}
    <p>There are no plants made yet.</p>
  {% endif %}
  
{% endblock %}

Plant_database_app/plant_view/templates/plant_view/planttype_confirm_delete.html
{% extends "navbar.html" %}

{% block content %}

<h1>Delete Plant</h1>

<p>Are you sure you want to delete the plant type: {{ planttype }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

Plant_database_app/plant_view/templates/plant_view/planttype_detail.html
{% extends "navbar.html" %}

{% block content %}

<span style="float: right;">
    {% comment %} {% if ad.owner == user %} {% endcomment %}
        <a href="{% url 'plant_view:planttype_update' planttype.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'plant_view:planttype_delete' planttype.id %}"><i class="fa fa-trash"></i></a>
    {% comment %} {% endif %} {% endcomment %}
</span>

<h1>{{ planttype.name }}</h1>

<p>Plant count: {{ plantcount }}</p>

{% endblock %}

Plant_database_app/plant_view/templates/plant_view/planttype_form.html
{% extends "navbar.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Submit">
        <input type="submit" onclick="javascript:history.go(-1);" value="Cancel">
    </form>
{% endblock %}

Plant_database_app/plant_view/templates/plant_view/planttype_list.html
{% extends "navbar.html" %}

{% block content %}
  <h1>Plant Types</h1>

  {% if planttype_list %}
  <ul>
    {% for planttype in planttype_list %}
      <li>
        <a href="{% url 'plant_view:planttype_detail' planttype.id %}">{{ planttype.name }}</a>
          (<a href="{% url 'plant_view:planttype_update' planttype.id %}">Edit</a> |
          <a href="{% url 'plant_view:planttype_delete' planttype.id %}">Delete</a>) <br/>
      </li>
    {% endfor %}
  </ul>

  {% else %}
    <p>There are no plant types made yet.</p>
  {% endif %}

  <p>_________________________________________________</p>
  <ul>
    <li><a href="{% url 'plant_view:planttype_create' %}">Add a new plant type!</a></li>
    <li><a href="{% url 'plant_view:all' %}">Go back to plants!</a></li>
  </ul>
{% endblock %}