Plant_database_app/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register', views.SignUpView.as_view(), name='register'),
]

Plant_database_app/plant_database/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('plant_view/', include('plant_view.urls')),
    path('', include('home.urls')),
]

Plant_database_app/plant_view/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "plant_view" # applicaition namespace
urlpatterns = [
        # Plant list, plant related urls:
        path('', views.MainView.as_view(), name='all'),
        path('main/myplants/', views.MyPlantsView.as_view(), name='plant_myplants'),
        path('main/create/', views.PlantCreateView.as_view(), name='plant_create'),
        path('main/<int:pk>/', views.PlantDetailView.as_view(), name='plant_detail'),
        path('main/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant_update'),
        path('main/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant_delete'),

        # Plant type related urls:
        path('ptview', views.PlantTypeListView.as_view(), name='planttype_list'),
        path('ptview/<int:pk>/', views.PlantTypeDetailView.as_view(), name='planttype_detail'),
        path('ptview/create/', views.PlantTypeCreate.as_view(), name='planttype_create'),
        path('ptview/<int:pk>/update/', views.PlantTypeUpdate.as_view(), name='planttype_update'),
        path('ptview/<int:pk>/delete/', views.PlantTypeDelete.as_view(), name='planttype_delete'),

        # Plant timeline related urls:
        path('main/<int:pk>/createevent/', views.PlantEventCreateView.as_view() , name='plantevent_create'),
        # path('ptevent/<int:pk>/update/', , name='planteventupdate'),
        # path('ptevent/<int:pk>/delete/', , name='plantevent_delete'),
    ]

Plant_database_app/home/models.py
from django.db import models

# Create your models here.

Plant_database_app/home/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    # Email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username','email','password1','password2'] 

Plant_database_app/home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.conf import settings
from django.contrib.auth.forms import *
from django.contrib.auth import login

from .forms import RegistrationForm

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations
class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

class SignUpView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'home/register.html', { 'form': form })
        
    def post(self, request):
        form = RegistrationForm(request.POST) 
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('')
        else:
            return render(request, 'home/register.html', {'form': form})

Plant_database_app/home/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
        <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

        <meta name="dj4e-version" content="2024-11-07">

        {% block head %} {% endblock %}

    </head>
    <body>
        <div class="container">
        {% block navbar %} {% endblock %}
        {% block welcome %} {% endblock %}
        {% block messages %}
            {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{msg.level_tag}}" role="alert">
                {{msg.message}}
                </div>
            {% endfor %}
            {% endif %}
        {% endblock %}

        {% block content %}
        {% endblock %}
        
        </div>
        {% block footer %} {% endblock %}
    </body>
</html>

Plant_database_app/home/templates/navbar.html
{% extends "base.html" %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-radius:10px !important">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">{{ settings.APP_NAME }}</a>

      {% comment %} ALL PLANTS LINK {% endcomment %}
      <ul class="navbar-nav">
        {% url 'plant_view:all' as x %}
        <li {% if request.get_full_path == x %}class="active"{% endif %}>
            <a class="nav-link" href="{% url 'plant_view:all' %}" role="button">Plants</a></li>
      </ul>

      {% comment %} PLANT TYPE LIST LINK {% endcomment %}
      <ul class="navbar-nav">
          <li {% if request.get_full_path == x %}class="active"{% endif %}>
              <a class="nav-link" href="{% url 'plant_view:planttype_list' %}" role="button">Plant types</a></li>
      </ul>
      
      {% comment %} MY PLANTS LINK {% endcomment %}
      <ul class="navbar-nav">
        <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'plant_view:plant_myplants' %}" role="button">My plants</a></li>
        </ul>
      </ul>

      {% comment %} USER LOGIN {% endcomment %}
      <ul class="navbar-nav">
        {% if user.is_authenticated %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% comment %} <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b> {% endcomment %}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
                <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'home:home' %}">Logout</a></li>
            </ul>
          </li>

         {% else %}
          {% comment %} USER LOGIN OR SIGNUP {% endcomment %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User Login
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
              <li><a class="dropdown-item" href="{% url 'login' %}?next={% url 'home:home' %}">Log in</a></li>
              <li><a class="dropdown-item" href="{% url 'home:register' %}">Sign up</a></li>
            </ul>
         </li>
         {% endif %}
         
      </ul>
    </div>
  </nav>
{% endblock %}